# terminal
set -g default-terminal "tmux-256color"

# baseIndex = 1
set -g base-index 1
setw -g pane-base-index 1

# escapeTime = 10
set -sg escape-time 10

# keyMode = "vi"
setw -g mode-keys vi
set -g status-keys vi

# shortcut = "Space"
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# extraConfig
set -g status-left '[#S]'
set -g status-left-length 20
set -g status-right ""
set -g status-position top
set -g status-style bg=black,fg=white
